### ISSUE TITLE
ERR_INVALID_CALLBACK

### ISSUE THREAD

**Issue by vitalyster** [loqui/im#1265]
```
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:136:9)
    at Object.writeFile (fs.js:1179:14)
    at Object.done (/Users/vt/Documents/im/renderersCompiler.js:18:8)
    at /Users/vt/Documents/im/node_modules/jsdom/lib/jsdom.js:259:18
    at process.internalTickCallback (internal/process/next_tick.js:70:11
```

```
$ node --version
v11.1.0
```

**Comment by nfsprodriver** [comment]
I recommend you to use node 6 lts. Does it work with that? I adjusted the wiki now as there were many fails with higher versions. Thanks for reporting!

**Comment by vitalyster** [comment]
Please check my PR, and adjust wiki back :)
