### ISSUE TITLE
How to install loqui on UbuntuTouch ?

### ISSUE THREAD

**Issue by nephilim1973** [loqui/im#660]
Hi folks,

like to install loqui on BQ Aquaris 4.5, but its unclear, where to place the www folder.
Could you provide a short 'howto' for me ?

Many thanks!
Nephilim

**Comment by nephilim1973** [comment]
While testing "loqui" as a local desktop installation on Ubuntu 14.04 with Firefox, the account registration does not work... (for all services... WhatApp, Faceboot, Google, etc.)

Calling URL    file://home/user/Dokumente/loqui/index.html

shows the messenger logo and than the account list.
Trying to register fails.

Please provide me with a little cookbook help.
Thanks!

**Comment by gargsms** [comment]
@nephilim1973  You should build the client to install it on Ubuntu Touch.
I am assuming you have nodejs, npm and grunt-cli installed.
Navigate to your git repository in the terminal and run

> $ npm install
> $ grunt

This should install the necessary node modules and build the app for you. You can then install the correct app from the **package** directory.

And regarding testing from desktop installation, some APIs that are needed for proper functioning are not either implemented in the desktop browsers, or are vulnerable. You should be able to login to Facebook though.

**Comment by nephilim1973** [comment]
Many thanks for fast reply. I will test it and will give a short success story (hopefuly :-)

**Comment by nephilim1973** [comment]
Unfortunatelly, I am running into problems...

What I did:

# sudo apt-get install make nodejs-legacy

# cd Downloads

# wget https://github.com/npm/npm/archive/master.zip

# unzip master.zip

# cd npm-master

# ./configure

# sudo make install

--> SUCCESS ! 

# cd ..

# wget https://github.com/loqui/im/archive/dev.zip

# unzip dev.zip

# cd im-dev

# sudo npm install

npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc32-stream
 
> pre-commit@1.0.6 install /home/phablet/Downloads/im-dev/node_modules/pre-commit
> node install.js

 
> contextify@0.1.13 install /home/phablet/Downloads/im-dev/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:103:14)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:42:11
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:40:25)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:43:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:54:16
stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Linux 3.4.0-4-goldfish
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/phablet/Downloads/im-dev/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.4.0-4-goldfish
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.25
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/phablet/Downloads/im-dev/npm-debug.log

**Comment by TitanNano** [comment]
as the error log says, you need to install python.

**Comment by nephilim1973** [comment]
Thanks, I am a noob in app-devel   :-)

Ok, I have managed to build my "LoquiIM-v0.4.1-ubuntutouch.zip"

For all beginners, here is what I did:

```
sudo apt-get install make nodejs-legacy python g++

wget https://github.com/npm/npm/archive/master.zip

unzip master.zip

cd npm-master

./configure

sudo make install

--> OK ???

cd ..

wget https://github.com/loqui/im/archive/dev.zip

unzip dev.zip

cd im-dev

sudo npm install

--> OK ???

sudo npm install -g grunt-cli

grunt

cd package

-->   LoquiIM-v0.4.1-ubuntutouch.zip          ;-)

click build .

--> "Successfully built package in './com.ubuntu.loqui.im.loqui_v0.4.1a_all.click'."

cp manifest.json manifest.json_ORG

vi manifest.json
--> change 
"version": "v0.4.1a" 
to 
"version": "0.4.1a"

click build .

--> "Successfully built package in './com.ubuntu.loqui.im.loqui_0.4.1a_all.click'."

pkcon --allow-untrusted install-local com.ubuntu.loqui.im.loqui_0.4.1a_all.click

```

Unfortunatelly, after starting LOQUI, just a black screen appears.   :-(

**Comment by nephilim1973** [comment]
```
qtmir.applications: ApplicationManager::onProcessStarting - appId= "com.ubuntu.loqui.im.loqui_loqui"
qtmir.applications: ApplicationController::desktopFilePathForAppId - appId= "com.ubuntu.loqui.im.loqui_loqui"
qtmir.applications: Application::Application - appId= "com.ubuntu.loqui.im.loqui_loqui" state= 0
qtmir.applications: ApplicationManager::add - appId= "com.ubuntu.loqui.im.loqui_loqui"
qtmir.applications: ApplicationManager::focusApplication - appId= "com.ubuntu.loqui.im.loqui_loqui"
qtmir.applications: ApplicationManager::resumeApplication - appId= "com.ubuntu.loqui.im.loqui_loqui"
qtmir.applications: Application::setFocused - appId= "unity8-dash" focused= false
qtmir.applications: ApplicationManager::onAppDataChanged: Received  "focused"  update
qtmir.applications: ApplicationManager::focusedApplicationForStage 0
qtmir.applications: ApplicationManager::suspendApplication - appId= "unity8-dash"
qtmir.applications: Application::setState - appId= "unity8-dash" state= suspended
qtmir.sessions: Session::setState - session= qtmir::Session(0x9d48b28) state= suspended
qtmir.applications: ApplicationManager::onAppDataChanged: Received  "state"  update
qtmir.applications: ApplicationManager::resumeApplication - appId= "com.ubuntu.loqui.im.loqui_loqui"
qtmir.applications: Application::setFocused - appId= "com.ubuntu.loqui.im.loqui_loqui" focused= true
qtmir.applications: ApplicationManager::onAppDataChanged: Received  "focused"  update
qtmir.applications: ApplicationManager::move - from= 1 to= 0
qtmir.surfaces: MirSurfaceItem::updateMirSurfaceFocus false
qtmir.surfaces: MirSurfaceManager::onSurfaceAttributeChanged - surface= 0xa55d74c focus=unfocused
qtmir.applications: ApplicationManager::move after  "com.ubuntu.loqui.im.loqui_loqui,unity8-dash"
qtmir.applications: ApplicationManager::focusApplication - appId= "com.ubuntu.loqui.im.loqui_loqui"
qtmir.applications: ApplicationManager::resumeApplication - appId= "com.ubuntu.loqui.im.loqui_loqui"
qtmir.applications: Application::setFocused - appId= "com.ubuntu.loqui.im.loqui_loqui" focused= false
qtmir.applications: ApplicationManager::onAppDataChanged: Received  "focused"  update
qtmir.applications: ApplicationManager::focusedApplicationForStage 0
qtmir.applications: ApplicationManager::suspendApplication - appId= "com.ubuntu.loqui.im.loqui_loqui"
qtmir.applications: ApplicationManager::resumeApplication - appId= "com.ubuntu.loqui.im.loqui_loqui"
qtmir.applications: Application::setFocused - appId= "com.ubuntu.loqui.im.loqui_loqui" focused= true
qtmir.applications: ApplicationManager::onAppDataChanged: Received  "focused"  update
qtmir.applications: ApplicationManager::move - from= 0 to= 0
qtmir.sessions: Wakelock acquired "de29bacf-1b6a-4a43-87bb-d1c721fadf44"
qtmir.mir: SessionAuthorizer::connection_is_allowed - this= SessionAuthorizer(0x9996cb4) pid= 12203
qtmir.applications: ApplicationManager::authorizeSession - pid= 12203
qtmir.applications: TaskController::isApplicationPid - appId= "com.ubuntu.loqui.im.loqui_loqui" pid= 12203
qtmir.mir: SessionAuthorizer::configure_display_is_allowed - this= SessionAuthorizer(0x9996cb4) pid= 12203
qtmir.mir: SessionAuthorizer::screencast_is_allowed - this= SessionAuthorizer(0x9996cb4) pid= 12203
qtmir.mir: SessionAuthorizer::prompt_session_is_allowed - this= SessionAuthorizer(0x9996cb4) pid= 12203
qtmir.mir: SessionListener::starting - this= SessionListener(0x9995b54) session= 0xa53290c
qtmir.mir: SessionListener::focused - this= SessionListener(0x9995b54) session= 0xa53290c
qtmir.sessions: SessionManager::onSessionStarting - sessionName= QtUbuntu
qtmir.sessions: Session::Session()  "QtUbuntu"
qtmir.applications: Application::setSession - appId= "com.ubuntu.loqui.im.loqui_loqui" session= qtmir::Session(0x9f00bd0)
qtmir.sessions: Session::setState - session= qtmir::Session(0x9f00bd0) state= starting
qtmir.surfaces: MirSurfaceItem::stopFrameDropper surface =  qtmir::MirSurfaceItem (this = 0xa54ba70 , name= "" , parent = 0x9d78388 , geometry = QRectF(0,0 480x768) , z = 1 )
qtmir.applications: Application::onSessionSuspended - appId= "unity8-dash"
qtmir.applications: TaskController::suspend - appId= "unity8-dash"

** (process:2195): WARNING **: Unable to get pids for 'unity8-dash' to send signal 19
ApplicationController::pauseApplication FAILED to pause appId= "unity8-dash"
qtmir.mir: MirPlacementStrategy: requested ( 1000 , 718 ) and returned ( 480 , 800 )
qtmir.mir: SessionListener::surface_created - this= SessionListener(0x9995b54) session= 0xa53290c surface= 0x9ea4fac
qtmir.mir: SessionListener::focused - this= SessionListener(0x9995b54) session= 0xa53290c
qtmir.surfaces: MirSurfaceManager::onSurfaceAttributeChanged - surface= 0x9ea4fac visibility=occluded
qtmir.applications: ApplicationManager::onSessionCreatedSurface - sessionName= QtUbuntu
qtmir.applications: Application::setState - appId= "com.ubuntu.loqui.im.loqui_loqui" state= running
qtmir.sessions: Session::setState - session= qtmir::Session(0x9f00bd0) state= running
qtmir.applications: ApplicationManager::onAppDataChanged: Received  "state"  update
qtmir.surfaces: MirSurfaceManager::onSessionCreatedSurface - mirSession= 0xa53290c surface= 0x9ea4fac surface.name= com.ubuntu.loqui.im.loqui
qtmir.surfaces: MirSurfaceItem::MirSurfaceItem
qtmir.sessions: Session::setSurface - session= "QtUbuntu" surface= qtmir::MirSurfaceItem (this = 0x9e31430 , name= "" , parent = 0x0 , geometry = QRectF(0,0 480x800) , z = 0 )
qtmir.sessions: Session::setFullscreen - session= qtmir::Session(0x9f00bd0) fullscreen= false
qtmir.surfaces: MirSurfaceManager::onSurfaceAttributeChanged - surface= 0x9ea4fac swapinterval=1
qtmir.surfaces: MirSurfaceItem::updateMirSurfaceFocus true
qtmir.surfaces: MirSurfaceManager::onSurfaceAttributeChanged - surface= 0x9ea4fac focus=focused
qtmir.surfaces: MirSurfaceItem::setOrientation - orientation= 0
qtmir.surfaces: MirSurfaceItem::updateMirSurfaceSize surface = qtmir::MirSurfaceItem (this = 0x9e31430 , name= "" , parent = 0xa08de50 , geometry = QRectF(0,0 480x768) , z = 1 ) , old ( 480 , 800 ) , new ( 480 , 768 ) surface resized
qtmir.clipboard: D-Bus GetContents - returning 0 bytes
qtmir.mir: SessionAuthorizer::connection_is_allowed - this= SessionAuthorizer(0x9996cb4) pid= 12372
qtmir.applications: ApplicationManager::authorizeSession - pid= 12372
qtmir.mir: SessionAuthorizer::configure_display_is_allowed - this= SessionAuthorizer(0x9996cb4) pid= 12372
qtmir.mir: SessionAuthorizer::screencast_is_allowed - this= SessionAuthorizer(0x9996cb4) pid= 12372
qtmir.mir: SessionAuthorizer::prompt_session_is_allowed - this= SessionAuthorizer(0x9996cb4) pid= 12372
qtmir.mir: SessionListener::starting - this= SessionListener(0x9995b54) session= 0x9eb128c
qtmir.mir: SessionListener::focused - this= SessionListener(0x9995b54) session= 0x9eb128c
qtmir.sessions: SessionManager::onSessionStarting - sessionName= QtUbuntu
qtmir.sessions: Session::Session()  "QtUbuntu"
```
