### ISSUE TITLE
[UbuntuTouch] installation fails in cause of version string

### ISSUE THREAD

**Issue by nephilim1973** [loqui/im#662]
Hi...

Because of a wrong version string in manifest.json, the click-installer/pkcon does not install the click-package.

Ubuntu needs at first a number in version string, but there comes a "v" at first.
Maybe "loqui.json" is involved, too.

```
sudo apt-get update
sudo apt-get install make nodejs-legacy python g++
cd ~/Downloads
wget https://github.com/npm/npm/archive/master.zip
unzip master.zip
cd npm-master
sudo make install
cd ..
wget https://github.com/loqui/im/archive/dev.zip
unzip dev.zip
cd im-dev
sudo npm install
sudo npm install -g grunt-cli
grunt
cd dist/ubuntu-touch
click build --no-validate .
pkcon --allow-untrusted install-local com.ubuntu.loqui.im.loqui_v0.4.1a_all.click
```

--> 

```
WARNING:root:Signature check failed, but installing anyway as requested
dpkg: Fehler beim Bearbeiten des Archivs com.ubuntu.loqui.im.loqui_v0.4.1a_all.click (--install):
 Parsen der Datei »/opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/v0.4.1a/.click/tmp.ci/control«, nahe Zeile 2 Paket »com.ubuntu.loqui.im.loqui«:
 Fehler in Zeichenkette »v0.4.1a« für Feld »Version«: Versionsnummer beginnt nicht mit einer Ziffer
Fehler traten auf beim Bearbeiten von:
 com.ubuntu.loqui.im.loqui_v0.4.1a_all.click
Traceback (most recent call last):
  File "/usr/bin/click", line 86, in <module>
    sys.exit(main())
  File "/usr/bin/click", line 82, in main
    return mod.run(args)
  File "/usr/lib/python3/dist-packages/click/commands/install.py", line 62, in run
    package_path, user=options.user, all_users=options.all_users)
  File "/usr/lib/python3/dist-packages/click/install.py", line 446, in install
    path, user=user, all_users=all_users)
  File "/usr/lib/python3/dist-packages/click/install.py", line 406, in _unpack
    env=env, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['dpkg', '--force-not-root', '--force-bad-path', '--force-architecture', '--instdir', '/opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/v0.4.1a', '--admindir', '/opt/click.ubuntu.com/com.ubuntu.loqui.im.loqui/v0.4.1a/.click', '--path-exclude', '*/.click/*', '--log', '/opt/click.ubuntu.com/.click/log', '--no-triggers', '--install', 'com.ubuntu.loqui.im.loqui_v0.4.1a_all.click']' returned non-zero exit status 1
```

**Comment by gargsms** [comment]
It would be great if you try to test it with the 'v' removed from the version number.
If it works, you can send a pull request. :smile:

**Comment by nephilim1973** [comment]
Hi gargsms...
I have tried this at first... 
Have removed the 'v' in manifest.json version string.
Installation succeeded, but I am not sure, if application is working as expected:

https://github.com/loqui/im/issues/663

On my desktop, loqui is looking great. But on UbuntuTouch I only get "black screens" or HTML pages.
Regards.

**Comment by Gioyik** [comment]
Hi, I tried to port LoquiIM time ago to Ubuntu Touch but it was hard due the emulator was not really useful and the sdk only works on Ubuntu (I think this is a big fail), so now I am sure there are outdated configurations. I migrated from Ubuntu to another Linux system so will be hard to update it but I will help on whatever I can.

**Comment by nephilim1973** [comment]
Hi... could you please explain "outdated configurations" in detail ? So I could gather all missing informations for you... Regards.

**Comment by nephilim1973** [comment]
Many thanks. I will test it soon.

**Comment by nephilim1973** [comment]
Solved ! Thanks a lot.

**Comment by TitanNano** [comment]
no problem 😉
